	
// Array of products, each product is an object with different fieldset
// A set of ingredients should be added to products		 

var products = [
	{
		name: "broccoli",
		vegetarian: true,
		gluten: true,
		organic: true,
		price: 3.99,
		deal: 0.0,
		drink: false,
		fridge: false,
		microwave: false,
		oven: false,
		dish: false,
		phone: false,
		tablet: false,
		computer: false,
		watch: false,
		shoes: false,
		jacket: false,
		pants: false,
		bag: false,
		description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque auctor, est et efficitur dapibus, mi nulla bibendum turpis, at facilisis quam orci eget ex. Vivamus nec nibh urna. Vivamus ac tristique ex. Mauris quis lectus sem. Integer dapibus leo vel elit hendrerit auctor. Morbi sit amet lorem a lectus porttitor convallis in non urna. Praesent lacus purus, semper rutrum pulvinar quis, varius at nibh. Proin non accumsan velit."
	},
	{
		name: "cabbage",
		vegetarian: true,
		gluten: true,
		organic: true,
		price: 2.35,
		deal: 0.0,
		drink: false,
		fridge: false,
		microwave: false,
		oven: false,
		dish: false,
		phone: false,
		tablet: false,
		computer: false,
		watch: false,
		shoes: false,
		jacket: false,
		pants: false,
		bag: false,
		description: "Nulla et massa fermentum felis dignissim tempus in at augue. Fusce consectetur arcu non ante finibus, pellentesque rutrum libero tincidunt. Pellentesque venenatis diam eget eros dignissim fringilla. Curabitur sollicitudin quam ex, luctus efficitur nisl porta in. Aenean a turpis bibendum orci sagittis mollis. Duis ut ullamcorper augue. Nunc id tincidunt elit. Donec porta ullamcorper efficitur. In scelerisque efficitur lorem ac mollis. Donec est neque, faucibus nec felis non, congue lacinia massa. Nam non porta urna."
	},
	{
		name: "corn",
		vegetarian: true,
		gluten: false,
		organic: true,
		price: 5.99,
		deal: 0.0,
		drink: false,
		fridge: false,
		microwave: false,
		oven: false,
		dish: false,
		phone: false,
		tablet: false,
		computer: false,
		watch: false,
		shoes: false,
		jacket: false,
		pants: false,
		bag: false,
		description: "Quisque eleifend justo sed porta laoreet. Morbi laoreet ante vel eros aliquet, et commodo justo lobortis. Fusce interdum laoreet volutpat. Nam molestie malesuada tellus, et gravida ex. Quisque iaculis maximus erat fringilla porttitor. Vestibulum accumsan sed urna a condimentum. Sed tristique luctus dolor, non suscipit sem finibus sed. Phasellus finibus tortor metus, id aliquet ante vulputate eget. Duis aliquam, ligula venenatis porttitor dictum, lorem diam dapibus libero, sit amet egestas metus arcu sit amet nibh. Nam a nisi at ante aliquam dictum."
	},
	{
		name: "salmon",
		vegetarian: false,
		gluten: true,
		organic: true,
		price: 23.50,
		deal: 0.0,
		drink: false,
		fridge: false,
		microwave: false,
		oven: false,
		dish: false,
		phone: false,
		tablet: false,
		computer: false,
		watch: false,
		shoes: false,
		jacket: false,
		pants: false,
		bag: false,
		description: "Nam blandit, lacus in tempor commodo, est elit volutpat elit, in vestibulum eros nisi ac ligula. Curabitur ac tellus purus. Nulla in nisi magna. In congue ante non ligula condimentum laoreet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec posuere leo neque. Donec elementum sodales imperdiet. Nam odio eros, auctor non metus condimentum, volutpat sollicitudin lectus."
	},
	{
		name: "milk",
		vegetarian: true,
		gluten: true,
		organic: true,
		price: 3.99,
		deal: 0.0,
		drink: true,
		fridge: false,
		microwave: false,
		oven: false,
		dish: false,
		phone: false,
		tablet: false,
		computer: false,
		watch: false,
		shoes: false,
		jacket: false,
		pants: false,
		bag: false,
		description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque auctor, est et efficitur dapibus, mi nulla bibendum turpis, at facilisis quam orci eget ex. Vivamus nec nibh urna. Vivamus ac tristique ex. Mauris quis lectus sem. Integer dapibus leo vel elit hendrerit auctor. Morbi sit amet lorem a lectus porttitor convallis in non urna. Praesent lacus purus, semper rutrum pulvinar quis, varius at nibh. Proin non accumsan velit."
	},
	{
		name: "fridge",
		vegetarian: false,
		gluten: false,
		organic: false,
		price: 2.35,
		deal: 0.0,
		drink: false,
		fridge: true,
		microwave: false,
		oven: false,
		dish: false,
		phone: false,
		tablet: false,
		computer: false,
		watch: false,
		shoes: false,
		jacket: false,
		pants: false,
		bag: false,
		description: "Nulla et massa fermentum felis dignissim tempus in at augue. Fusce consectetur arcu non ante finibus, pellentesque rutrum libero tincidunt. Pellentesque venenatis diam eget eros dignissim fringilla. Curabitur sollicitudin quam ex, luctus efficitur nisl porta in. Aenean a turpis bibendum orci sagittis mollis. Duis ut ullamcorper augue. Nunc id tincidunt elit. Donec porta ullamcorper efficitur. In scelerisque efficitur lorem ac mollis. Donec est neque, faucibus nec felis non, congue lacinia massa. Nam non porta urna."
	},
	{
		name: "microwave",
		vegetarian: false,
		gluten: false,
		organic: false,
		price: 5.99,
		deal: 0.0,
		drink: false,
		fridge: false,
		microwave: true,
		oven: false,
		dish: false,
		phone: false,
		tablet: false,
		computer: false,
		watch: false,
		shoes: false,
		jacket: false,
		pants: false,
		bag: false,
		description: "Quisque eleifend justo sed porta laoreet. Morbi laoreet ante vel eros aliquet, et commodo justo lobortis. Fusce interdum laoreet volutpat. Nam molestie malesuada tellus, et gravida ex. Quisque iaculis maximus erat fringilla porttitor. Vestibulum accumsan sed urna a condimentum. Sed tristique luctus dolor, non suscipit sem finibus sed. Phasellus finibus tortor metus, id aliquet ante vulputate eget. Duis aliquam, ligula venenatis porttitor dictum, lorem diam dapibus libero, sit amet egestas metus arcu sit amet nibh. Nam a nisi at ante aliquam dictum."
	},
	{
		name: "oven",
		vegetarian: false,
		gluten: false,
		organic: false,
		price: 4.35,
		deal: 0.0,
		drink: false,
		fridge: false,
		microwave: false,
		oven: true,
		dish: false,
		phone: false,
		tablet: false,
		computer: false,
		watch: false,
		shoes: false,
		jacket: false,
		pants: false,
		bag: false,
		description: "Fusce tempus viverra placerat. Nullam ut nunc urna. Aliquam dictum mauris interdum odio condimentum molestie. Praesent eget elementum purus. Morbi vitae lectus eget sem ultrices egestas. Mauris ut eros commodo quam commodo varius ac id justo. Etiam ipsum dolor, sodales vitae quam eget, efficitur ullamcorper sapien. Nullam justo nibh, laoreet sed magna at, fermentum euismod massa. Etiam hendrerit eu turpis eget finibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce interdum sed odio a porttitor."
	},
	{
		name: "dishwasher",
		vegetarian: false,
		gluten: false,
		organic: false,
		price: 1.99,
		deal: 0.0,
		drink: false,
		fridge: false,
		microwave: false,
		oven: false,
		dish: true,
		phone: false,
		tablet: false,
		computer: false,
		watch: false,
		shoes: false,
		jacket: false,
		pants: false,
		bag: false,
		description: "Sed eget lacus dignissim, euismod sapien condimentum, pharetra odio. Curabitur id eros ac ligula pulvinar ullamcorper. Quisque tempus nibh quis tortor ornare, eget volutpat quam egestas. Morbi tempus, lectus eget bibendum dapibus, turpis lacus consectetur neque, vitae dapibus urna tortor sit amet ex. Mauris sagittis nibh nec nulla bibendum luctus. Nunc non mattis purus. Duis vehicula maximus mauris ut efficitur. Aliquam sit amet augue nec enim dictum blandit."
	},
	{
		name: "phone",
		vegetarian: false,
		gluten: false,
		organic: false,
		price: 2.35,
		deal: 0.0,
		drink: false,
		fridge: false,
		microwave: false,
		oven: false,
		dish: false,
		phone: true,
		tablet: false,
		computer: false,
		watch: false,
		shoes: false,
		jacket: false,
		pants: false,
		bag: false,
		description: "Suspendisse potenti. Vivamus porta ligula sed nunc facilisis, fringilla ultricies lacus scelerisque. Aliquam libero nibh, aliquet non erat nec, sodales commodo mauris. Sed vitae ex dapibus, sagittis lorem eu, porttitor lorem. Duis dictum laoreet dignissim. Morbi lorem augue, faucibus et ipsum eget, commodo venenatis ex. Nunc lacinia quam id ultrices blandit. Nullam fringilla erat eget maximus maximus. Phasellus in euismod diam. Ut eu massa enim. Morbi velit ex, convallis et massa a, vulputate posuere leo. Nunc faucibus, augue efficitur ullamcorper euismod, turpis nisl pharetra lectus, non vehicula lorem odio dictum neque. Vestibulum in libero sapien. Pellentesque at lorem lacinia, placerat leo vitae, pellentesque tortor. Aliquam sit amet interdum ipsum. Cras ut interdum justo."
	},
	{
		name: "tablet",
		vegetarian: false,
		gluten: false,
		organic: false,
		price: 1.99,
		deal: 0.0,
		drink: false,
		fridge: false,
		microwave: false,
		oven: false,
		dish: false,
		phone: false,
		tablet: true,
		computer: false,
		watch: false,
		shoes: false,
		jacket: false,
		pants: false,
		bag: false,
		description: "Nullam ac tristique tellus. Nam eget ex eget leo blandit suscipit. Duis a lorem luctus, ornare nisi pharetra, finibus massa. Aenean felis enim, placerat ac urna vel, tempus pharetra nibh. Donec sodales dui nisi, vel scelerisque nulla aliquet in. Nullam volutpat sapien non fermentum posuere. Vivamus felis sapien, ultricies ac imperdiet vel, pretium eu neque. Quisque a leo eros."
	},
	{
		name: "computer",
		vegetarian: false,
		gluten: false,
		organic: false,
		price: 2.35,
		deal: 0.0,
		drink: false,
		fridge: false,
		microwave: false,
		oven: false,
		dish: false,
		phone: false,
		tablet: false,
		computer: true,
		watch: false,
		shoes: false,
		jacket: false,
		pants: false,
		bag: false,
		description: "Curabitur vestibulum lorem at turpis faucibus varius. Nulla a varius quam. Vivamus sit amet tellus ut nulla pharetra tristique ut rutrum ex. Vivamus vehicula placerat nibh, elementum elementum magna convallis at. Aenean in tempor est, ac sodales tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque sed mattis lacus. Suspendisse consectetur semper orci. Pellentesque vestibulum orci quis ipsum pellentesque, sed eleifend tellus fringilla. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce dictum nisl et faucibus congue."
	},
	{
		name: "watch",
		vegetarian: false,
		gluten: false,
		organic: false,
		price: 10.00,
		deal: 0.0,
		drink: false,
		fridge: false,
		microwave: false,
		oven: false,
		dish: false,
		phone: false,
		tablet: false,
		computer: false,
		watch: true,
		shoes: false,
		jacket: false,
		pants: false,
		bag: false,
		description: "Fusce sollicitudin turpis dignissim odio tempus, eget pulvinar eros laoreet. Praesent suscipit eget nisl at lacinia. Aenean vehicula fringilla nunc at lacinia. Fusce vitae turpis vitae magna aliquam sollicitudin sit amet et ante. Vestibulum laoreet diam ullamcorper augue dictum, vel gravida velit faucibus. Donec eget consectetur mi, id maximus augue. Sed ante neque, rhoncus vitae aliquam vitae, pellentesque non mauris. Nunc nec nunc ipsum. Quisque at enim et sapien dictum semper. Morbi ut magna eget leo ullamcorper tempus. Aenean rutrum lobortis neque sed rhoncus. Integer luctus libero et odio posuere, posuere vestibulum risus feugiat. Sed tristique nec lorem et ultrices. Donec euismod quam a quam convallis, sollicitudin porttitor dolor semper. Praesent porta euismod porta."
	},
	{
		name: "shoes",
		vegetarian: false,
		gluten: false,
		organic: false,
		price: 23.50,
		deal: 0.0,
		drink: false,
		fridge: false,
		microwave: false,
		oven: false,
		dish: false,
		phone: false,
		tablet: false,
		computer: false,
		watch: false,
		shoes: true,
		jacket: false,
		pants: false,
		bag: false,
		description: "Nam blandit, lacus in tempor commodo, est elit volutpat elit, in vestibulum eros nisi ac ligula. Curabitur ac tellus purus. Nulla in nisi magna. In congue ante non ligula condimentum laoreet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec posuere leo neque. Donec elementum sodales imperdiet. Nam odio eros, auctor non metus condimentum, volutpat sollicitudin lectus."
	},
	{
		name: "jacket",
		vegetarian: false,
		gluten: false,
		organic: false,
		price: 2.35,
		deal: 0.0,
		drink: false,
		fridge: false,
		microwave: false,
		oven: false,
		dish: false,
		phone: false,
		tablet: false,
		computer: false,
		watch: false,
		shoes: false,
		jacket: true,
		pants: false,
		bag: false,
		description: "Curabitur vestibulum lorem at turpis faucibus varius. Nulla a varius quam. Vivamus sit amet tellus ut nulla pharetra tristique ut rutrum ex. Vivamus vehicula placerat nibh, elementum elementum magna convallis at. Aenean in tempor est, ac sodales tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque sed mattis lacus. Suspendisse consectetur semper orci. Pellentesque vestibulum orci quis ipsum pellentesque, sed eleifend tellus fringilla. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce dictum nisl et faucibus congue."
	},
	{
		name: "brussel sprouts",
		vegetarian: true,
		gluten: true,
		organic: true,
		price: 4.35,
		deal: 0.0,
		drink: false,
		fridge: false,
		microwave: false,
		oven: false,
		dish: false,
		phone: false,
		tablet: false,
		computer: false,
		watch: false,
		shoes: false,
		jacket: false,
		pants: false,
		bag: false,
		description: "Fusce tempus viverra placerat. Nullam ut nunc urna. Aliquam dictum mauris interdum odio condimentum molestie. Praesent eget elementum purus. Morbi vitae lectus eget sem ultrices egestas. Mauris ut eros commodo quam commodo varius ac id justo. Etiam ipsum dolor, sodales vitae quam eget, efficitur ullamcorper sapien. Nullam justo nibh, laoreet sed magna at, fermentum euismod massa. Etiam hendrerit eu turpis eget finibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce interdum sed odio a porttitor."
	},
	{
		name: "eggs",
		vegetarian: false,
		gluten: true,
		organic: true,
		price: 1.99,
		deal: 0.0,
		drink: false,
		fridge: false,
		microwave: false,
		oven: false,
		dish: false,
		phone: false,
		tablet: false,
		computer: false,
		watch: false,
		shoes: false,
		jacket: false,
		pants: false,
		bag: false,
		description: "Sed eget lacus dignissim, euismod sapien condimentum, pharetra odio. Curabitur id eros ac ligula pulvinar ullamcorper. Quisque tempus nibh quis tortor ornare, eget volutpat quam egestas. Morbi tempus, lectus eget bibendum dapibus, turpis lacus consectetur neque, vitae dapibus urna tortor sit amet ex. Mauris sagittis nibh nec nulla bibendum luctus. Nunc non mattis purus. Duis vehicula maximus mauris ut efficitur. Aliquam sit amet augue nec enim dictum blandit."
	},
	{
		name: "puding",
		vegetarian: false,
		gluten: false,
		organic: false,
		price: 2.35,
		deal: 0.0,
		drink: false,
		fridge: false,
		microwave: false,
		oven: false,
		dish: false,
		phone: false,
		tablet: false,
		computer: false,
		watch: false,
		shoes: false,
		jacket: false,
		pants: false,
		bag: false,
		description: "Suspendisse potenti. Vivamus porta ligula sed nunc facilisis, fringilla ultricies lacus scelerisque. Aliquam libero nibh, aliquet non erat nec, sodales commodo mauris. Sed vitae ex dapibus, sagittis lorem eu, porttitor lorem. Duis dictum laoreet dignissim. Morbi lorem augue, faucibus et ipsum eget, commodo venenatis ex. Nunc lacinia quam id ultrices blandit. Nullam fringilla erat eget maximus maximus. Phasellus in euismod diam. Ut eu massa enim. Morbi velit ex, convallis et massa a, vulputate posuere leo. Nunc faucibus, augue efficitur ullamcorper euismod, turpis nisl pharetra lectus, non vehicula lorem odio dictum neque. Vestibulum in libero sapien. Pellentesque at lorem lacinia, placerat leo vitae, pellentesque tortor. Aliquam sit amet interdum ipsum. Cras ut interdum justo."
	},
	{
		name: "clementine",
		vegetarian: true,
		gluten: true,
		organic: true,
		price: 1.99,
		deal: 0.0,
		drink: false,
		fridge: false,
		microwave: false,
		oven: false,
		dish: false,
		phone: false,
		tablet: false,
		computer: false,
		watch: false,
		shoes: false,
		jacket: false,
		pants: false,
		bag: false,
		description: "Nullam ac tristique tellus. Nam eget ex eget leo blandit suscipit. Duis a lorem luctus, ornare nisi pharetra, finibus massa. Aenean felis enim, placerat ac urna vel, tempus pharetra nibh. Donec sodales dui nisi, vel scelerisque nulla aliquet in. Nullam volutpat sapien non fermentum posuere. Vivamus felis sapien, ultricies ac imperdiet vel, pretium eu neque. Quisque a leo eros."
	},
	{
		name: "bread",
		vegetarian: true,
		gluten: false,
		organic: false,
		price: 2.35,
		deal: 0.0,
		drink: false,
		fridge: false,
		microwave: false,
		oven: false,
		dish: false,
		phone: false,
		tablet: false,
		computer: false,
		watch: false,
		shoes: false,
		jacket: false,
		pants: false,
		bag: false,
		description: "Curabitur vestibulum lorem at turpis faucibus varius. Nulla a varius quam. Vivamus sit amet tellus ut nulla pharetra tristique ut rutrum ex. Vivamus vehicula placerat nibh, elementum elementum magna convallis at. Aenean in tempor est, ac sodales tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque sed mattis lacus. Suspendisse consectetur semper orci. Pellentesque vestibulum orci quis ipsum pellentesque, sed eleifend tellus fringilla. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce dictum nisl et faucibus congue."
	},
	{
		name: "tofu",
		vegetarian: true,
		gluten: true,
		organic: true,
		price: 10.00,
		deal: 0.0,
		drink: false,
		fridge: false,
		microwave: false,
		oven: false,
		dish: false,
		phone: false,
		tablet: false,
		computer: false,
		watch: false,
		shoes: false,
		jacket: false,
		pants: false,
		bag: false,
		description: "Fusce sollicitudin turpis dignissim odio tempus, eget pulvinar eros laoreet. Praesent suscipit eget nisl at lacinia. Aenean vehicula fringilla nunc at lacinia. Fusce vitae turpis vitae magna aliquam sollicitudin sit amet et ante. Vestibulum laoreet diam ullamcorper augue dictum, vel gravida velit faucibus. Donec eget consectetur mi, id maximus augue. Sed ante neque, rhoncus vitae aliquam vitae, pellentesque non mauris. Nunc nec nunc ipsum. Quisque at enim et sapien dictum semper. Morbi ut magna eget leo ullamcorper tempus. Aenean rutrum lobortis neque sed rhoncus. Integer luctus libero et odio posuere, posuere vestibulum risus feugiat. Sed tristique nec lorem et ultrices. Donec euismod quam a quam convallis, sollicitudin porttitor dolor semper. Praesent porta euismod porta."
	},
	{
		name: "pants",
		vegetarian: false,
		gluten: false,
		organic: false,
		price: 10.00,
		deal: 0.0,
		drink: false,
		fridge: false,
		microwave: false,
		oven: false,
		dish: false,
		phone: false,
		tablet: false,
		computer: false,
		watch: false,
		shoes: false,
		jacket: false,
		pants: true,
		bag: false,
		description: "Fusce sollicitudin turpis dignissim odio tempus, eget pulvinar eros laoreet. Praesent suscipit eget nisl at lacinia. Aenean vehicula fringilla nunc at lacinia. Fusce vitae turpis vitae magna aliquam sollicitudin sit amet et ante. Vestibulum laoreet diam ullamcorper augue dictum, vel gravida velit faucibus. Donec eget consectetur mi, id maximus augue. Sed ante neque, rhoncus vitae aliquam vitae, pellentesque non mauris. Nunc nec nunc ipsum. Quisque at enim et sapien dictum semper. Morbi ut magna eget leo ullamcorper tempus. Aenean rutrum lobortis neque sed rhoncus. Integer luctus libero et odio posuere, posuere vestibulum risus feugiat. Sed tristique nec lorem et ultrices. Donec euismod quam a quam convallis, sollicitudin porttitor dolor semper. Praesent porta euismod porta."
	},
	{
		name: "bag",
		vegetarian: false,
		gluten: false,
		organic: false,
		price: 23.50,
		deal: 0.0,
		drink: false,
		fridge: false,
		microwave: false,
		oven: false,
		dish: false,
		phone: false,
		tablet: false,
		computer: false,
		watch: false,
		shoes: false,
		jacket: false,
		pants: false,
		bag: true,
		description: "Nam blandit, lacus in tempor commodo, est elit volutpat elit, in vestibulum eros nisi ac ligula. Curabitur ac tellus purus. Nulla in nisi magna. In congue ante non ligula condimentum laoreet. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec posuere leo neque. Donec elementum sodales imperdiet. Nam odio eros, auctor non metus condimentum, volutpat sollicitudin lectus."
	}

];

var cartProductPriceLst = [];

var cartProductNameLst = [];

var cartProductAmountLst = [];
	

// Calculate the total price of items, with received parameter being a list of products
function getTotalPrice(chosenProducts) {
	totalPrice = 0;

	for (var i = 0; i < chosenProducts.length; i = i + 2) {
		for (var j = 0; j < products.length; j++) {
			if (chosenProducts[i] == products[j].name) {
				// alert(products[j].name);
				totalPrice += products[j].price * chosenProducts[i+1];
			}
		}
	}

	return totalPrice.toFixed(2);
}

